# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170619_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_faveroute',
            field=models.BooleanField(default=False),
        ),
    ]
